In [20]:
import pandas as pd
import json
import numpy as np

In [ ]:


# 1. Tentukan path ke file Load Ready
file_path = "data/reports/Load_Ready_20260401_1344.csv"

print(f"Membaca file dari {file_path} ...")
# 2. Baca CSV
df_ready = pd.read_csv(file_path)
print(f"Total baris awal: {len(df_ready):,}")

# 3. Ekstrak data JSON ke dalam format kolom
print("Parsing Row_Data_JSON...")
# Menggunakan trik dict comprehension & list comprehension untuk parse JSON
parsed_data = [json.loads(row) for row in df_ready["Row_Data_JSON"]]

# 4. Buat DataFrame baru berdasarkan data yang sudah diekstrak
# Lalu gabungkan dengan 'Dataset_Id' dan 'Judul_Tabel' dari yang aslinya
df_extracted = pd.DataFrame(parsed_data)

# Agar kita tahu baris ini asalnya dari dataset mana
df_final = pd.concat([
    df_ready[["Dataset_Id", "Judul_Tabel"]],
    df_extracted
], axis=1)

print("Proses selesai!")
display(df_final.head())

Membaca file dari data/reports/Load_Ready_20260401_1344.csv ...
Total baris awal: 148,843
Parsing Row_Data_JSON...
Proses selesai!

,Dataset_Id,Judul_Tabel,tahun,instansi,subdomain,tahun_pembuatan,status,dataset_id,kab_kota,jenis_komoditas,...,nama_pasar_rakyat,jumlah_pasar_rakyat,luas_rhl,aktiva,aktiva_tetap,utang_jangka_pendek,utang_jangka_panjang,dana_cadangan,jumlah_ekuitas,jmlh_kec
0,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,2021,Aparatur Sipil Negara Provinsi Jawa Tengah,asn.jatengprov.go.id,2016.0,Aktif,164ecc1e-d029-49cd-807a-94d48dc621a4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,2021,Government Resources Management System Provins...,grms.jatengprov.go.id,2016.0,Aktif,164ecc1e-d029-49cd-807a-94d48dc621a4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,2021,Budaya Lapor Boss RSJD Dr. Amino Gondohutomo S...,laporbos.rs-amino.jatengprov.go.id,2016.0,Aktif,164ecc1e-d029-49cd-807a-94d48dc621a4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,2021,-,mail.e-dokum.jatengprov.go.id,2016.0,Aktif,164ecc1e-d029-49cd-807a-94d48dc621a4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,2021,Aparatur Sipil Negara Provinsi Jawa Tengah,asn.jatengprov.go.id,2016.0,Aktif,164ecc1e-d029-49cd-807a-94d48dc621a4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df_final.tail()

,Dataset_Id,Judul_Tabel,tahun,instansi,subdomain,tahun_pembuatan,status,dataset_id,kab_kota,jenis_komoditas,...,nama_pasar_rakyat,jumlah_pasar_rakyat,luas_rhl,aktiva,aktiva_tetap,utang_jangka_pendek,utang_jangka_panjang,dana_cadangan,jumlah_ekuitas,jmlh_kec
148838,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,Jumlah Murid Taman Kanak - Kanak ( TK ) di Baw...,2025,NaN,NaN,NaN,NaN,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148839,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,Jumlah Murid Taman Kanak - Kanak ( TK ) di Baw...,2025,NaN,NaN,NaN,NaN,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148840,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,Jumlah Murid Taman Kanak - Kanak ( TK ) di Baw...,2025,NaN,NaN,NaN,NaN,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148841,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,Jumlah Murid Taman Kanak - Kanak ( TK ) di Baw...,2025,NaN,NaN,NaN,NaN,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148842,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,Jumlah Murid Taman Kanak - Kanak ( TK ) di Baw...,2025,NaN,NaN,NaN,NaN,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_filter = df_final[["Dataset_Id", "Judul_Tabel", "tahun"]].copy()
df_filter['tahun'] = df_filter['tahun'].astype("int")

In [5]:
df_filter['tahun'].value_counts()

tahun
2024       47291
2022       25391
2023       21188
2021       15519
2019       15093
2020       13152
2025        9959
2017         262
2018         184
33           174
2015         171
2014         163
1            107
2016         101
34            36
2013          35
2026           8
7              3
2              2
3              2
1367433        1
193200         1
Name: count, dtype: int64

In [15]:
df_tahun = df_filter[(df_filter["tahun"] >= 2019) & (df_filter["tahun"] <= 2026)]
df_tahun.sort_values(by="tahun", ascending=False)
df_tahun["tahun"].value_counts()

tahun
2024    47291
2022    25391
2023    21188
2021    15519
2019    15093
2020    13152
2025     9959
2026        8
Name: count, dtype: int64

In [17]:
df_encoded = pd.get_dummies(df_tahun, columns=['tahun'])
df_encoded.head()

,Dataset_Id,Judul_Tabel,tahun_2019,tahun_2020,tahun_2021,tahun_2022,tahun_2023,tahun_2024,tahun_2025,tahun_2026
0,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,False,False,True,False,False,False,False,False
1,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,False,False,True,False,False,False,False,False
2,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,False,False,True,False,False,False,False,False
3,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,False,False,True,False,False,False,False,False
4,164ecc1e-d029-49cd-807a-94d48dc621a4,Jumlah Sub Domain Provinsi Jawa Tengah,False,False,True,False,False,False,False,False

In [31]:
df_combined = df_encoded.groupby(["Judul_Tabel", "Dataset_Id"]).any().reset_index()
cols_to_fix = df_combined.columns.difference(['Judul_Tabel', 'Dataset_Id'])
df_combined[cols_to_fix] = np.where(df_combined[cols_to_fix], "Tersedia", "Tidak Tersedia")
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921 entries, 0 to 920
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Judul_Tabel  921 non-null    object
 1   Dataset_Id   921 non-null    object
 2   tahun_2019   921 non-null    object
 3   tahun_2020   921 non-null    object
 4   tahun_2021   921 non-null    object
 5   tahun_2022   921 non-null    object
 6   tahun_2023   921 non-null    object
 7   tahun_2024   921 non-null    object
 8   tahun_2025   921 non-null    object
 9   tahun_2026   921 non-null    object
dtypes: object(10)
memory usage: 72.1+ KB

In [32]:
df_combined.head()

,Judul_Tabel,Dataset_Id,tahun_2019,tahun_2020,tahun_2021,tahun_2022,tahun_2023,tahun_2024,tahun_2025,tahun_2026
0,\tData Indeks Demokrasi Indonesia Jawa Tengah,8601f0f2-c01f-4323-806d-ee027722720b,Tidak Tersedia,Tidak Tersedia,Tersedia,Tersedia,Tersedia,Tidak Tersedia,Tidak Tersedia,Tidak Tersedia
1,"\tJumlah Sekolah ,Guru Taman Kanak - Kanak ( T...",f49fe359-747f-41f4-a47b-5cf1e3c04a20,Tidak Tersedia,Tidak Tersedia,Tidak Tersedia,Tidak Tersedia,Tidak Tersedia,Tersedia,Tersedia,Tidak Tersedia
2,Jumlah Guru Perkab/Kota Berdasarkan Status Ke...,7df079f5-121c-47b6-a249-565a7f3be13d,Tidak Tersedia,Tidak Tersedia,Tidak Tersedia,Tidak Tersedia,Tidak Tersedia,Tersedia,Tidak Tersedia,Tidak Tersedia
3,ASN di Lingkungan Pemerintah Provinsi Jawa Tengah,fb0540ab-2f02-4976-bf0a-f9d0e69cde29,Tersedia,Tersedia,Tersedia,Tersedia,Tersedia,Tidak Tersedia,Tidak Tersedia,Tidak Tersedia
4,Alokasi APBD Provinsi Jawa Tengah,d3aa4fe1-3352-4b0d-bff8-2b2008ccea5d,Tersedia,Tersedia,Tersedia,Tersedia,Tersedia,Tersedia,Tidak Tersedia,Tidak Tersedia

In [34]:
df_combined.to_excel("data/reports/data_ketersediaan_per_tahun.xlsx")

In [50]:
df_filter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148843 entries, 0 to 148842
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Dataset_Id   148843 non-null  object
 1   Judul_Tabel  148843 non-null  object
 2   tahun        148843 non-null  int32
dtypes: int32(1), object(2)
memory usage: 2.8+ MB

In [51]:
# filter tahun hanya dari 2024 sampai 2025 saja
df_filter = df_filter[df_filter['tahun'] >= 2024]
df_filter.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57260 entries, 2470 to 148842
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Dataset_Id   57260 non-null  object
 1   Judul_Tabel  57260 non-null  object
 2   tahun        57260 non-null  int32
dtypes: int32(1), object(2)
memory usage: 1.5+ MB

In [55]:
df_cleaned = df_filter.drop_duplicates(subset=['Dataset_Id'], keep="last")
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 727 entries, 2474 to 148842
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Dataset_Id   727 non-null    object
 1   Judul_Tabel  727 non-null    object
 2   tahun        727 non-null    int32
dtypes: int32(1), object(2)
memory usage: 19.9+ KB

In [65]:
df_cleaned[df_cleaned["tahun"] == 2025]

,Dataset_Id,Judul_Tabel,tahun
7115,32bd0554-b810-44ca-ac25-d1d4932cb265,Realisasi Investasi PMA di Jawa Tengah Berdas...,2025
7357,298656d9-acaf-4460-9ed5-234a078354fc,Realisasi Investasi PMA di Jawa Tengah Berdas...,2025
8020,3534d7ea-58a7-4730-a949-54e963ce163b,Realisasi Investasi PMDN di Jawa Tengah Berdas...,2025
8517,a24bf3eb-0fb2-40ac-b50a-49087f83db7c,Realisasi Investasi PMA di Jawa Tengah Berdas...,2025
11256,3ae89859-9720-4c79-9235-bafa5d43c5df,Data Unjuk Rasa,2025
...,...,...,...
148417,401246c5-5440-4fc9-a05e-7e07514395de,Data Pasar Rakyat di Jawa Tengah (Data Pembang...,2025
148452,805daa52-9480-4ba6-a3f9-5b4c755a64ef,Luas hutan dan lahan yang terehabilitasi secar...,2025
148702,f49fe359-747f-41f4-a47b-5cf1e3c04a20,"\tJumlah Sekolah ,Guru Taman Kanak - Kanak ( T...",2025
148772,5cefe7d0-697e-415d-9d63-3ae94c8b6108,Jumlah Kecamatan Menurut Kabupaten/Kota di Pro...,2025
148842,fdf786a1-0097-4f0b-92fd-c77e7dfaa6ac,Jumlah Murid Taman Kanak - Kanak ( TK ) di Baw...,2025

In [60]:
df_cleaned.to_excel("data/reports/data_filter(2024&2025).xlsx")